apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: test-runner-binding
  namespace: default
subjects:
- kind: ServiceAccount
  name: test-runner
  namespace: default
roleRef:
  kind: Role
  name: test-runner-role
  apiGroup: rbac.authorization.k8s.io