apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: test-runner-role
  namespace: default
rules:
- apiGroups: [""]
  resources: ["services", "endpoints"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]